config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: %I[index show], param: :username

  scope shallow_path: "problems" do
    resources :problems do
      resources :comments, shallow: true, only: %I[create edit update destroy]
      resources :solutions, shallow: true, only: %I[index show new create destroy]
    end
  end

  root to: "problems#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :problem
  belongs_to :user
end

app/models/problem.rb
class Problem < ApplicationRecord
  PER_PAGE = 12
  paginates_per PER_PAGE

  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true

  has_many :comments, dependent: :destroy
  has_many :solutions, dependent: :destroy
  has_many :views, dependent: :destroy
end

app/models/solution.rb
class Solution < ApplicationRecord
  validates :code, presence: true

  belongs_to :user
  belongs_to :problem
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  PER_PAGE = 24
  paginates_per PER_PAGE

  has_many :problems, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :solutions, dependent: :destroy
  has_many :views, dependent: :destroy

  validates :username, presence: true, uniqueness: true

  def to_param
    username
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    User.where(email: data.email).first || User.create(
      username: data.name,
      email: data.email,
      password: Devise.friendly_token
    )
  end
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :problem
  belongs_to :user
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  include Pundit
  protect_from_forgery

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not allowed to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose :problem, id: :problem_id
  expose :comment
  before_action :authorize_comment, only: %I[update destroy]

  def edit; end

  def create
    result = Comments::Create.call(comment_params.merge(user: current_user, problem: problem))
    if result.success?
      respond_with result.comment, problem_location
    else
      redirect_to problem, alert: result.error
    end
  end

  def update
    comment.update(comment_params)
    respond_with comment, problem_location
  end

  def destroy
    comment.destroy
    respond_with comment, problem_location
  end

  private

  def problem_location
    { location: -> { problem_path(comment.problem_id || problem.id) } }
  end

  def authorize_comment
    authorize comment
  end

  def comment_params
    params.require(:comment).permit(:problem_id, :user_id, :text)
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  expose :problem
  before_action :authorize_problem, only: %I[show new edit update destroy]
  before_action :authenticate_user!, only: %I[new edit create destroy]

  def index
    @problems = Problem.order("created_at").page(params[:page] || 1)
  end

  def show
    Views::Create.call(user: current_user, problem: problem)
  end

  def new; end

  def edit; end

  def create
    problem.user = current_user
    authorize problem
    problem.save
    respond_with problem
  end

  def update
    problem.update(problem_params)
    respond_with problem
  end

  def destroy
    problem.destroy
    respond_with problem
  end

  private

  def authorize_problem
    authorize problem
  end

  def problem_params
    params.require(:problem).permit(:title, :description, :user_id)
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  expose :problem, id: :problem_id
  expose :solution
  expose :solutions, from: :problem
  before_action :authorize_solution, only: %I[show edit update destroy]
  before_action :authenticate_user!

  def index
    authorize solutions
  end

  def show; end

  def new; end

  def create
    solution.user = current_user
    solution.problem = problem
    solution.save
    respond_with solution
  end

  def destroy
    solution.destroy
    respond_with solution, location: -> { problem_path(solution.problem_id) }
  end

  private

  def authorize_solution
    authorize solution
  end

  def solution_params
    params.require(:solution).permit(:code)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      auth_data = request.env["omniauth.auth"]
      @user = User.from_omniauth(auth_data)
      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Google"
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.google_data"] = auth_data.except(:extra)
        redirect_to new_user_registration_url, flash: @user.errors
      end
    end

    def failure
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page] || 1)
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_path(problem)
    problem_comments_path(problem)
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
  def solutions_path(problem)
    problem_solutions_path(problem)
  end

  def new_solution_path(problem)
    new_problem_solution_path(problem)
  end
end

app/views/comments/_comment.html.slim
- decorated_comment = comment.decorate

.card.mb-3
  .card-body
    p.card-text = render "layouts/markdown", html: decorated_comment.text_html, cached: true
    .row
      .col
        p.card-text
          small.text-muted
            | by
            =<> decorated_comment.author_link
            | at
            =< decorated_comment.created_at
      .col
        - if policy(comment).edit?
          = link_to t("common.edit"), edit_comment_path(comment), class: "card-link"
        - if policy(comment).destroy?
          = link_to t("common.destroy"), comment,
                          method: :delete,
                          data: { confirm: t("common.confirmation") },
                          class: "card-link"

app/views/comments/_comments.html.slim
.mt-2
  h3 = t("comments.label.plural")
  .container
    = render comments
  - if policy(:comment).new?
    .mt-2
      = render "comments/new_form", comment: current_user.comments.new(problem: problem)

app/views/comments/_edit_form.html.slim
= render "comments/form", comment: comment, form_url: comment_path(comment)

app/views/comments/_form.html.slim
= simple_form_for(comment, url: form_url) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.input :text, label: t("comments.actions.new")
  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/comments/_new_form.html.slim
= render "comments/form", comment: comment, form_url: comments_path(comment.problem_id)

app/views/comments/edit.html.slim
h1 = t("comments.actions.edit")

.clearfix
  = render comment.problem

.mt-4
  = render "comments/edit_form", comment: comment

.mt-4
  = link_to t("common.back"), comment.problem

app/views/layouts/_flashes.html.slim
.mt-4
  - flash.each do |key, value|
    = content_tag :div, value, class: "flash #{key} alert-danger", role: "alert"

app/views/layouts/_markdown.html.slim
= html

app/views/layouts/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "Aphelcoma", problems_path, class: "navbar-brand"
  .collapse.navbar-collapse
    ul.navbar-nav
      li.nav-item
        = link_to "Problems", problems_path, class: "nav-link"
  ul.navbar-nav
    - if user_signed_in?
      li.nav-item
        = link_to "My account: #{current_user.email}", current_user, class: "nav-link"
      li.nav-item
        span.navbar-text = "/"
      li.nav-item
        = link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"
    - else
      li.nav-item
        = link_to "Log in", new_user_session_path, class: "nav-link"
      li.nav-item
        span.navbar-text = "/"
      li.nav-item
        = link_to "Join", new_user_registration_path, class: "nav-link"

app/views/layouts/_notice.html.slim
.mt-4
  - if notice
    .alert.alert-success#notice = notice
  - if alert
    .alert.alert-danger#alert = alert

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Aphelcoma
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    / script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    / script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    / script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  body
    = render "layouts/nav"
    .container.mb-4
      = render "layouts/notice"
      = yield

app/views/problems/_form.html.slim
= simple_form_for(problem) do |form|
  - if problem.errors.any?
    #error_explanation
      h2
        = pluralize(problem.errors.count, t("common.error"))
        |  prohibited this problem from being saved:
      ul
        - problem.errors.full_messages.each do |message|
          li = message
  .field
    = form.input :title
  .field
    = form.input :description,
                      as: :text,
                      label: t("problems.labels.description"),
                      input_html: { rows: 10, class: "text-monospace" }
  .actions
    = form.button :submit, class: "btn btn-primary"

app/views/problems/_problem.html.slim
- decorated_problem = problem.decorate

.problem.card.float-left
  .card-body
    h5.card-title = problem.title
    h6.card-subtitle.mb-2.text-muted
      = decorated_problem.author_link
    p.card-text.text-truncate = decorated_problem.preview
    = link_to t("common.show"), problem, class: "card-link"
    - if policy(problem).edit?
      = link_to t("common.edit"), edit_problem_path(problem), class: "card-link"
    - if policy(problem).destroy?
      = link_to t("common.destroy"),
                      problem,
                      method: :delete,
                      data: { confirm: t("common.confirmation") },
                      class: "card-link"
    .float-right = "👁 #{decorated_problem.views_count}"

app/views/problems/edit.html.slim
h1 = t("problems.actions.edit")

= render "form", problem: problem

= link_to t("common.show"), problem
= " | "
= link_to t("common.back"), problems_path

app/views/problems/index.html.slim
h1 = t("problems.label.plural")

.container.clearfix = render @problems

= paginate @problems
.clearfix
  - if policy(:problem).new?
    .float-right = link_to t("problems.actions.new"), new_problem_path, class: "btn btn-outline-primary"

app/views/problems/new.html.slim
h1 = t("problems.actions.new")
= render "form", problem: problem
= link_to t("common.back"), problems_path

app/views/problems/show.html.slim
- decorated_problem = problem.decorate

h2 = problem.title
p.small
  = "#{t('common.published')} #{decorated_problem.created_at}, "
  = decorated_problem.author_link
p
  = render "layouts/markdown", html: decorated_problem.text_html, cached: true
.clearfix
  .float-left
    = link_to t("common.back"), problems_path, class: "card-link"
    - if policy(problem).edit?
      = link_to t("common.edit"), edit_problem_path(problem), class: "card-link"
    - if policy(problem).destroy?
      = link_to t("common.destroy"), problem,
                      method: :delete,
                      data: { confirm: t("common.confirmation") },
                      class: "card-link"
  .float-right
    - if policy(problem.solutions).index?
      => link_to t("solutions.label.single"), solutions_path(problem)
    - if policy(:solution).new?
      => link_to t("solutions.actions.new"),
                      new_solution_path(problem),
                      class: "btn btn-outline-success"
    = pluralize(decorated_problem.views_count, t("views.label.single"))

.mb-4
  = render "comments/comments", comments: decorated_problem.comments, problem: problem

app/views/solutions/_form.html.slim
= simple_form_for(solution, url: form_url) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    .field
      = f.input :code,
                      as: :text,
                      input_html: { rows: 10, class: "text-monospace" }
  .custom-file.mb-4
    input.custom-file-input#codeFileInput type="file"
    label.custom-file-label for="codeFileInput" = t("solutions.actions.upload")
  .form-actions
    .float-right
      = f.button :submit, class: "btn btn-success"

= javascript_pack_tag "solutions"

app/views/solutions/_new_form.html.slim
= render "form", problem: problem, form_url: solutions_path(problem.id)

app/views/solutions/_solution.html.slim
- decorated_solution = solution.decorate

.problem.card.float-left
  .card-body
    p.card-title
      | by
      = decorated_solution.author_link
    p.card-text
      pre
        = decorated_solution.code
    .clearfix
      .float-left
        - if policy(solution).show?
          => link_to t("solutions.actions.show"), solution, class: "btn btn-link"
      .float-right
        - if policy(solution).destroy?
          =< link_to t("common.destroy"), solution,
                          method: :delete,
                          data: { confirm: t("common.confirmation") },
                          class: "btn btn-danger"

app/views/solutions/index.html.slim
h1
  = t("solutions.actions.index")
  i =< problem.title

.clearfix.mt-4
  = render solutions

.clearfix
  .float-left
    = link_to t("common.back"), problem
  .float-right
    = link_to t("solutions.actions.new"), new_solution_path(problem), class: "btn btn-outline-primary"

app/views/solutions/new.html.slim
h1 = t("solutions.actions.new")
.clearfix
  = render "new_form", problem: problem
  .float-left
    = link_to t("common.back"), problem

app/views/solutions/show.html.slim
- decorated_solution = solution.decorate

p
  strong
    | For
    i =< decorated_solution.problem_title
p
  strong
    | by
    =< decorated_solution.author_name
p
  pre = solution.code
= link_to t("common.back"), solutions_path(solution.problem_id)

app/views/users/_user.html.slim
- decorated_user = user.decorate

.card
  .card-body
    = decorated_user.link

app/views/users/index.html.slim
h1 = t("users.label.plural")

.container = render @users

= paginate @users
br

app/views/users/show.html.slim
.row
  h1 = @user.username
  - if @user == current_user
    = link_to t("users.actions.edit"), edit_user_registration_url, class: "small"

= render @user.problems